version: "3.9"

services:
  backend:
    image: nowork-backend:latest
    restart: unless-stopped
    env_file:
      - ../.env.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ../data/ip2region.xdb:/app/ip2region.xdb:ro
    depends_on:
      - mysql
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: change_me_prod
      MYSQL_DATABASE: nowork
      MYSQL_USER: nowork
      MYSQL_PASSWORD: change_me_prod
    volumes:
      - ../data/mysql:/var/lib/mysql
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../logs/nginx:/var/log/nginx
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
