services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
      target: runner
    image: nowork-backend:latest
    restart: unless-stopped
    env_file:
      - ../.env.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ../data/ip2region.xdb:/app/ip2region.xdb:ro
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ../.env.prod
    volumes:
      - ../data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ../data/redis:/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    image: nowork-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ../logs/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
